application: remail-wasauce-demo
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+ 
  script: main.py 
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: .*
  script: main.py

inbound_services:
- mail